name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

defaults:
  run:
    working-directory: ./rust

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Free disk space
        run: |
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install mold linker
        uses: rui314/setup-mold@v1
        with:
          mold-version: 2.0.0
          make-default: true
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'v2-rust'
          shared-key: 'e2e'
          workspaces: |
            ./rust
      - name: node module cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
      - name: build test
        run: cargo build --release --bin run-locally
      - name: run test
        run: ./target/release/run-locally
        env:
          E2E_CI_MODE: 'true'
          E2E_CI_TIMEOUT_SEC: '600'
          E2E_KATHY_MESSAGES: '20'
